obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[0.2, 0.2], [0.2, -0.2], [-0.2, -0.2], [-0.2, 0.2]]
inflation_radius: 0.55

observation_sources: laser_scan_sensor

laser_scan_sensor: {
    sensor_frame: lidar_link,
    data_type: LaserScan,
    topic: /laser/scan,
    marking: true,
    clearing: true
  }