footprint: [[0.2, 0.2], [0.2, -0.2], [-0.2, -0.2], [-0.2, 0.2]]
inflation_radius: 0

observation_sources: laser_scan_sensor

obstacle_range: 5
laser_scan_sensor: {
    sensor_frame: camera_depth_frame,
    data_type: LaserScan,
    topic: /scan,
    marking: true
  }

global_frame: odom
robot_base_frame: base_link
update_frequency: 5.0
publish_frequency: 2.0
static_map: false
rolling_window: false
width: 50.0
height: 50.0
resolution: 0.05
origin_x: -12
origin_y: 0
