obstacle_range: 3.0
raytrace_range: 2.0
footprint: [[0.3, 0.3], [0.3, -0.3], [-0.3, -0.3], [-0.3, 0.3]]
inflation_radius: 0.5

observation_sources: laser_scan_sensor

laser_scan_sensor: {
    sensor_frame: lidar_link,
    data_type: LaserScan,
    topic: /laser/scan,
    marking: true,
    clearing: true
  }