# Joystic configuration for Logitech F310 gamepad
axes_map:
  roll: 2
  pitch: 3
  yaw: 0
  throttle: 1
axes_scale:
  roll: 1.0
  pitch: 1.0
  yaw: 1.0
  throttle: 1.0
button_map:
  takeoff: 0
  land: 1
  enable: 2
rc_modes:
  offboard:
    rc_channel: 4
    rc_value: 1000
    joy_flags: [ [2,1] ]
  auto:
    rc_channel: 4
    rc_value: 1500
    joy_flags: [ [3,1] ]
  manual:
    rc_channel: 4
    rc_value: 2000
    joy_flags: [ [0,1] ]
